# -*- coding: utf-8 -*-
"""DataLoader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVWMfUDA0dVfRzhpwVdMYPBauqxuuzhU
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Major Project

import pandas as pd
import numpy as np

import sys

sys.executable

class DataLoader():
  def __init__(self,path_vid,path_lables,path_train=None,path_val=None,path_test=None):
    self.path_vid=path_vid
    self.path_labels=path_lables
    self.path_train=path_train
    self.path_val=path_val
    self.path_test=path_test

    self.get_labels(path_lables)

    if self.path_train:
      self.train_df = self.load_video_labels(self.path_train)
    if self.path_val:
      self.val_df =self.load_video_labels(self.path_val)
    if self.path_test:
      self.test_df=self.load_video_labels(self.path_val)

  def getlabels(self,path_labels):
    self.labels_df =pd.read_csv(path_labels,names=['labels'])
    #extract labels from data frames
    self.labels=[str(label[0]) for label in self.label_df.values]
    self.n_labels=len(self.labels)
    #create dict. to convert label to int and backwards
    self.label_to_int = dict(zip(self.labels,range(self.n_labels)))
    self.int_to_labels = dict(enumerate(self.labels))
    dictionary = {0:value}

  def load_video_labels(self,path_subset,mode='label'):
    if mode=='input':
        names=['video_id']
    elif mode=='label':
        names==['video_id','label']

    df =pd.read_csv(path_subset,sep=';',names=names)

    if mode=='label':
      df=df[df.label.isin(self.labels)]


  #def catgerocial_to_label(self):



self.labels_df = pd.read_csv(path_labels, names=['label'])  # Or specific encoding you find
